project:
  type: website

website:
  title: "PyTorch_intro"
  navbar:
  
    left:
      - text: Main_Blog
        href: https://sjoon0305.github.io/sj_hub/
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sjoon0305
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css:
      - styles.css
      - |
        .output {
          max-height: 300px; /* 최대 높이를 설정 */
          overflow-y: auto;  /* 세로 스크롤을 추가하여 넘치는 부분을 스크롤로 볼 수 있도록 함 */
        }